class AddIndexToRoles< ActiveRecord::Migration
  def change
    add_column :role_model_relations, :num, :bigint
    add_index :capitals, :created_at
    add_index :car_brands, :created_at
    add_index :car_models, :created_at
    add_index :car_nums, :created_at
    add_index :cities, :created_at
    add_index :customer_num_relations, :created_at
    add_index :goal_sale_types, :created_at
    add_index :image_urls, :created_at
    add_index :m_order_types, :created_at
    add_index :mat_order_items, :created_at
    add_index :menus, :created_at
    add_index :order_pay_types, :created_at
    add_index :order_prod_relations, :created_at
    add_index :pcard_prod_relations, :created_at
    add_index :prod_mat_relations, :created_at
    add_index :res_prod_relations, :created_at
    add_index :revisit_order_relations, :created_at
    add_index :role_menu_relations, :created_at
    add_index :role_model_relations, :created_at
    add_index :roles, :created_at
    add_index :sale_prod_relations, :created_at
    add_index :send_messages, :created_at
    add_index :staff_role_relations, :created_at
    add_index :svcard_prod_relations, :created_at
    add_index :train_staff_relations, :created_at
    add_index :c_pcard_relations, :updated_at
    add_index :c_svc_relations, :updated_at
    add_index :car_brands, :updated_at
    add_index :car_models, :updated_at
    add_index :car_nums, :updated_at
    add_index :chart_images, :updated_at
    add_index :cities, :updated_at
    add_index :customer_num_relations, :updated_at
    add_index :goal_sale_types, :updated_at
    add_index :goal_sales, :updated_at
    add_index :image_urls, :updated_at
    add_index :m_order_types, :updated_at
    add_index :mat_in_orders, :updated_at
    add_index :mat_order_items, :updated_at
    add_index :mat_out_orders, :updated_at
    add_index :menus, :updated_at
    add_index :message_records, :updated_at
    add_index :notices, :updated_at
    add_index :order_pay_types, :updated_at
    add_index :order_prod_relations, :updated_at
    add_index :pcard_prod_relations, :updated_at
    add_index :prod_mat_relations, :updated_at
    add_index :res_prod_relations, :updated_at
    add_index :reservations, :updated_at
    add_index :revisit_order_relations, :updated_at
    add_index :role_menu_relations, :updated_at
    add_index :role_model_relations, :updated_at
    add_index :roles, :updated_at
    add_index :salaries, :updated_at
    add_index :salary_details, :updated_at
    add_index :sale_prod_relations, :updated_at
    add_index :send_messages, :updated_at
    add_index :staff_gr_records, :updated_at
    add_index :staff_role_relations, :updated_at
    add_index :station_staff_relations, :updated_at
    add_index :svcard_prod_relations, :updated_at
    add_index :svcard_use_records, :updated_at
    add_index :train_staff_relations, :updated_at
    add_index :trains, :updated_at
    add_index :wk_or_times, :updated_at
    add_index :work_orders, :updated_at
    add_index :work_records, :updated_at
    add_index :work_records, :created_at
    add_index :violation_rewards, :created_at
    add_index :staff_gr_records, :created_at
    add_index :orders, :created_at
    add_index :mat_in_orders, :created_at
    add_index :mat_out_orders, :created_at
    add_index :suppliers, :created_at
    add_index :stores, :created_at
    add_index :sales, :created_at
    add_index :reservations, :created_at
    add_index :goal_sales, :created_at
    add_index :news, :created_at
    add_index :package_cards, :created_at
    add_index :package_cards, :updated_at
    add_index :svc_return_records, :created_at
    add_index :chart_images, :created_at
  end
end
